upate yml file

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -1,26 +1,35 @@
-# This references a standard debian container from the
-# Docker Hub https://registry.hub.docker.com/_/debian/
-# Read more about containers on our dev center
-# http://devcenter.wercker.com/docs/containers/index.html
-box: debian
-# You can also use services such as databases. Read more on our dev center:
-# http://devcenter.wercker.com/docs/services/index.html
-# services:
-    # - postgres
-    # http://devcenter.wercker.com/docs/services/postgresql.html
-
-    # - mongodb
-    # http://devcenter.wercker.com/docs/services/mongodb.html
-
-# This is the build pipeline. Pipelines are the core of wercker
-# Read more about pipelines on our dev center
-# http://devcenter.wercker.com/docs/pipelines/index.html
-build:
-    # Steps make up the actions in your pipeline
-    # Read more about steps on our dev center:
-    # http://devcenter.wercker.com/docs/steps/index.html
-  steps:
-    - script:
-        name: echo
-        code: |
-          echo "hello world!"
+name: java
+version: 0.1.3
+inherits: wercker/ubuntu12.04-webessentials@0.0.5
+type: main
+platform: ubuntu@12.04
+description: Wercker box for Java development
+packages:
+  - oracle-java8
+script: |-
+  # Remove java from base box
+  sudo apt-get purge openjdk-\* icedtea-\* icedtea6-\*
+  
+  # Assert that java is not available anymore
+  ! type java || { echo "I expected java to be not available. Java version is: $(java -version). Aborting."; exit 1; }
+  # Add webupd8 team repository that contains the 3 major oracle-java versions
+  sudo add-apt-repository ppa:webupd8team/java -y
+  sudo apt-get update
+  # Accept the oracle license
+  echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
+  echo debconf shared/accepted-oracle-license-v1-1 seen true |  sudo debconf-set-selections
+  
+  # Install oracle-java7
+  sudo apt-get install oracle-java7-installer -y -qq
+  
+  # We should have java again
+  type java || { echo "I expected java to be available after oracle-java8-installer installation. Aborting."; exit 1; }
+  # Install ant
+  sudo apt-get install ant ant-contrib ivy ivy-doc -y -qq
+  
+  # We should have ant and ivy available
+  type ant || { echo "I expected ant to be available. Aborting."; exit 1; }
+  # Install maven
+  sudo apt-get install maven -y -qq
+  
+  type mvn || { echo "I expected maven to be available. Aborting."; exit 1; }
